[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
workingDirectory = "shogoconnect-api"
cmds = ["npm ci"]

[phases.build]
workingDirectory = "shogoconnect-api"
cmds = []

[start]
cmd = "node shogoconnect-api/index.js"