const comments = [
    {
      id: 1,
      content: "Superbe introduction au Shogi ! J'apprécie vraiment le fait que tu aies pris le temps d'expliquer les bases en détail. Cela m'a permis de mieux comprendre les principes fondamentaux du jeu. Je me sens maintenant plus confiant pour commencer une partie. Merci beaucoup !",
      TopicId: 1,
      UserId: 10,
    },
    {
      id: 2,
      content: "Je ne suis pas tout à fait d'accord avec ton explication. Certains points sont un peu vagues, mais cela reste une bonne base pour les débutants.",
      TopicId: 2,
      UserId: 25,
    },
    {
      id: 3,
      content: "Merci pour ces explications ! C'était très clair et bien présenté.",
      TopicId: 3,
      UserId: 18,
    },
    {
      id: 4,
      content: "Je suis toujours un peu confus sur la règle de promotion des pièces, mais je vais revoir tes explications.",
      TopicId: 4,
      UserId: 5,
    },
    {
      id: 5,
      content: "J'ai beaucoup appris grâce à cette discussion, merci !",
      TopicId: 5,
      UserId: 12,
    },
    {
      id: 6,
      content: "J'aimerais avoir plus de détails sur les stratégies intermédiaires. Peut-on approfondir ce sujet ?",
      TopicId: 6,
      UserId: 23,
    },
    {
      id: 7,
      content: "Très bon sujet, merci pour cette discussion !",
      TopicId: 7,
      UserId: 7,
    },
    {
      id: 8,
      content: "Je me demande si quelqu'un ici a des astuces pour améliorer sa défense.",
      TopicId: 8,
      UserId: 14,
    },
    {
      id: 9,
      content: "Ton explication des ouvertures de jeu est très claire. Merci !",
      TopicId: 9,
      UserId: 32,
    },
    {
      id: 10,
      content: "Je pense qu'il y a encore des zones d'ombre sur les promotions, mais c'était utile quand même.",
      TopicId: 10,
      UserId: 16,
    },
    {
      id: 11,
      content: "Les parties en ligne sont toujours un peu compliquées pour moi, des conseils ?",
      TopicId: 11,
      UserId: 28,
    },
    {
      id: 12,
      content: "Merci pour ton aide. Ça m'a bien éclairé !",
      TopicId: 12,
      UserId: 21,
    },
    {
      id: 13,
      content: "J'aime bien les parties en mode rapide. Ça te force à réfléchir vite.",
      TopicId: 13,
      UserId: 11,
    },
    {
      id: 14,
      content: "Le système de pièces promues est vraiment intéressant dans le Shogi, mais complexe à maîtriser.",
      TopicId: 14,
      UserId: 24,
    },
    {
      id: 15,
      content: "Je commence à bien comprendre les bases, mais je galère encore avec les fins de partie.",
      TopicId: 15,
      UserId: 6,
    },
    {
      id: 16,
      content: "J'aime bien comment le jeu te pousse à réfléchir de manière stratégique.",
      TopicId: 16,
      UserId: 17,
    },
    {
      id: 17,
      content: "J'aimerais bien jouer contre des adversaires plus expérimentés pour progresser.",
      TopicId: 17,
      UserId: 33,
    },
    {
      id: 18,
      content: "J'ai découvert de nouvelles techniques grâce à toi, merci pour le partage.",
      TopicId: 18,
      UserId: 9,
    },
    {
      id: 19,
      content: "Superbe discussion, c'est très motivant de voir autant de passionnés.",
      TopicId: 19,
      UserId: 13,
    },
    {
      id: 20,
      content: "Les pièces du Shogi sont fascinantes. Chacune a un rôle unique à jouer.",
      TopicId: 20,
      UserId: 2,
    },
    {
      id: 21,
      content: "Merci pour cette explication détaillée sur les mouvements des pièces.",
      TopicId: 1,
      UserId: 4,
    },
    {
      id: 22,
      content: "Je m'entraîne régulièrement mais j'ai du mal à anticiper les mouvements adverses.",
      TopicId: 2,
      UserId: 29,
    },
    {
      id: 23,
      content: "Les jeux de stratégie comme le Shogi sont les meilleurs pour entraîner l'esprit.",
      TopicId: 3,
      UserId: 5,
    },
    {
      id: 24,
      content: "Je suis nouveau dans le jeu mais j'apprends rapidement grâce à ce forum.",
      TopicId: 4,
      UserId: 26,
    },
    {
      id: 25,
      content: "Les différentes variantes de Shogi sont vraiment intéressantes. J'aime bien le style rapide.",
      TopicId: 5,
      UserId: 19,
    },
    {
      id: 26,
      content: "Je n'avais jamais réalisé à quel point le Shogi est riche en stratégie.",
      TopicId: 6,
      UserId: 8,
    },
    {
    id: 27,
    content: "Je trouve la règle des promotions un peu difficile à saisir, mais je pense que ça viendra avec le temps.",
    TopicId: 7,
    UserId: 30,
    },
    {
    id: 28,
    content: "Est-ce que quelqu'un aurait des recommandations de livres pour améliorer sa stratégie au Shogi ?",
    TopicId: 8,
    UserId: 3,
    },
    {
    id: 29,
    content: "Merci pour cette discussion très intéressante sur l'ouverture de jeu.",
    TopicId: 9,
    UserId: 27,
    },
    {
    id: 30,
    content: "Je commence à comprendre comment utiliser les pièces défensives de manière plus efficace.",
    TopicId: 10,
    UserId: 20,
    },
    {
    id: 31,
    content: "C'est vraiment utile d'avoir ce genre de forum pour échanger sur le Shogi.",
    TopicId: 11,
    UserId: 15,
    },
    {
    id: 32,
    content: "La promotion des pièces est un des aspects les plus intrigants du Shogi. J'essaie de comprendre toutes les possibilités.",
    TopicId: 12,
    UserId: 31,
    },
    {
    id: 33,
    content: "Je suis content de voir autant de joueurs actifs ici !",
    TopicId: 13,
    UserId: 22,
    },
    {
    id: 34,
    content: "Comment gérez-vous les situations où vous êtes en désavantage ? J'ai du mal à reprendre le dessus.",
    TopicId: 14,
    UserId: 9,
    },
    {
    id: 35,
    content: "Merci pour ce forum. C'est un endroit génial pour améliorer ses compétences.",
    TopicId: 15,
    UserId: 34,
    },
    {
    id: 36,
    content: "Je viens juste de commencer à jouer au Shogi, et ces discussions m'aident beaucoup.",
    TopicId: 16,
    UserId: 2,
    },
    {
    id: 37,
    content: "J'aimerais savoir comment bien protéger mon roi en fin de partie.",
    TopicId: 17,
    UserId: 35,
    },
    {
    id: 38,
    content: "Ce forum est exactement ce qu'il me fallait pour améliorer mon jeu !",
    TopicId: 18,
    UserId: 10,
    },
    {
    id: 39,
    content: "Les discussions ici sont super enrichissantes. J'apprends beaucoup.",
    TopicId: 19,
    UserId: 8,
    },
    {
    id: 40,
    content: "J'ai encore des difficultés à comprendre certaines stratégies complexes.",
    TopicId: 20,
    UserId: 36,
    },
    {
    id: 41,
    content: "Je progresse bien grâce à vos conseils. Merci à tous.",
    TopicId: 1,
    UserId: 17,
    },
    {
    id: 42,
    content: "Le Shogi demande vraiment de la patience et de la concentration. C'est ce qui rend ce jeu si intéressant.",
    TopicId: 2,
    UserId: 12,
    },
    {
    id: 43,
    content: "J'apprécie la variété des conseils ici, on en apprend toujours plus.",
    TopicId: 3,
    UserId: 19,
    },
    {
    id: 44,
    content: "Les discussions ici m'ont aidé à comprendre des points que je n'avais pas saisis auparavant.",
    TopicId: 4,
    UserId: 23,
    },
    {
    id: 45,
    content: "Je me demande si on pourrait faire une partie amicale entre les membres de ce forum.",
    TopicId: 5,
    UserId: 6,
    },
    {
    id: 46,
    content: "J'ai beaucoup appris sur les mouvements de pièces grâce à vous tous.",
    TopicId: 6,
    UserId: 15,
    },
    {
    id: 47,
    content: "Ce forum est une ressource précieuse pour tous les joueurs de Shogi, peu importe leur niveau.",
    TopicId: 7,
    UserId: 39,
    },
    {
    id: 48,
    content: "Je suis content de voir autant de membres partager leurs connaissances.",
    TopicId: 8,
    UserId: 25,
    },
    {
    id: 49,
    content: "Les ouvertures de jeu sont fascinantes, j'aimerais les approfondir davantage.",
    TopicId: 9,
    UserId: 40,
    },
    {
    id: 50,
    content: "Merci à tous pour vos conseils. J'ai l'impression de progresser à chaque discussion.",
    TopicId: 10,
    UserId: 11,
    }
]

module.exports = comments;