topics = [
    {
        id: 1,
        title: "Introduction au Shogi",
        content: "Quelles sont les bases du Shogi que tout débutant devrait connaître ?",
        UserId: 1,
        CategoryId: 1,
    },
    {
        id: 2,
        title: "Les stratégies avancées",
        content: "Quels sont les concepts avancés du Shogi à maîtriser après les bases ?",
        UserId: 12,
        CategoryId: 3,
    },
    {
        id: 3,
        title: "Pièces de Shogi et leur mouvement",
        content: "Une question sur les mouvements de certaines pièces ?",
        UserId: 7,
        CategoryId: 2,
    },
    {
        id: 4,
        title: "Tournois de Shogi locaux",
        content: "Quels tournois sont prévus dans votre région ?",
        UserId: 9,
        CategoryId: 4,
    },
    {
        id: 5,
        title: "Les clubs de Shogi en France",
        content: "Découvrez les clubs locaux pour améliorer votre jeu.",
        UserId: 15,
        CategoryId: 4,
    },
    {
        id: 6,
        title: "Questions de débutant",
        content: "Quel est le meilleur conseil pour un joueur qui débute dans le Shogi ?",
        UserId: 20,
        CategoryId: 2,
    },
    {
        id: 7,
        title: "Progrès des débutants",
        content: "Partagez vos progrès et obtenez des conseils.",
        UserId: 25,
        CategoryId: 2,
    },
    {
        id: 8,
        title: "Feedback sur l'interface",
        content: "Que pensez-vous des améliorations récentes du site ?",
        UserId: 30,
        CategoryId: 5,
    },
    {
        id: 9,
        title: "Le Shogi pour les enfants",
        content: "Comment initier vos enfants au Shogi ?",
        UserId: 35,
        CategoryId: 1,
    },
    {
        id: 10,
        title: "Analyse de partie",
        content: "Partagez vos parties pour une analyse détaillée.",
        UserId: 40,
        CategoryId: 3,
    },
    {
        id: 11,
        title: "Les pièces spéciales",
        content: "Discutez des pièces rares et spéciales du Shogi.",
        UserId: 5,
        CategoryId: 1,
    },
    {
        id: 12,
        title: "Différences entre les variantes",
        content: "Comparons le Shogi avec d'autres variantes d'échecs.",
        UserId: 6,
        CategoryId: 6,
    },
    {
        id: 13,
        title: "Tournoi en ligne",
        content: "Quels sont les meilleurs sites pour les tournois de Shogi en ligne ?",
        UserId: 18,
        CategoryId: 4,
    },
    {
        id: 14,
        title: "Problèmes de jeu",
        content: "Partagez les problèmes que vous rencontrez avec l'interface du jeu.",
        UserId: 14,
        CategoryId: 5,
    },
    {
        id: 15,
        title: "Le Shogi dans la culture japonaise",
        content: "Explorez l'histoire et l'impact culturel du Shogi au Japon.",
        UserId: 10,
        CategoryId: 1,
    },
    {
        id: 16,
        title: "Pourquoi jouer au Shogi ?",
        content: "Quels sont les bénéfices de jouer au Shogi pour le développement intellectuel ?",
        UserId: 45,
        CategoryId: 1,
    },
    {
        id: 17,
        title: "Les erreurs courantes",
        content: "Quels sont les pièges à éviter pour les débutants ?",
        UserId: 2,
        CategoryId: 2,
    },
    {
        id: 18,
        title: "S'améliorer au Shogi",
        content: "Quels sont vos conseils pour améliorer votre niveau ?",
        UserId: 3,
        CategoryId: 2,
    },
    {
        id: 19,
        title: "Votre premier tournoi",
        content: "Partagez vos expériences de votre premier tournoi de Shogi.",
        UserId: 19,
        CategoryId: 4,
    },
    {
        id: 20,
        title: "Tournois en ligne",
        content: "Participez-vous à des tournois de Shogi en ligne ?",
        UserId: 11,
        CategoryId: 6,
    }
]

module.exports = topics;